name: Check the source code
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.10.1'
      - name: Install packages
        run: flutter pub get
      - name: Set up environment variables
        run: |
          echo "API_KEY_WEB=${{ secrets.API_KEY_WEB }}" >> $GITHUB_ENV
          echo "API_KEY_ANDROID=${{ secrets.API_KEY_ANDROID }}" >> $GITHUB_ENV
          echo "API_KEY_IOS=${{ secrets.API_KEY_IOS }}" >> $GITHUB_ENV
          echo "APP_ID_WEB=${{ secrets.APP_ID_WEB }}" >> $GITHUB_ENV
          echo "APP_ID_ANDROID=${{ secrets.APP_ID_ANDROID }}" >> $GITHUB_ENV
          echo "APP_ID_IOS=${{ secrets.APP_ID_IOS }}" >> $GITHUB_ENV
          echo "MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
      - name: Run the code generator
        run: flutter pub run build_runner build
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test
